values-de/strings.xml

Corrected typos and minor stylistic issues.

Corrections in 'de' resources

---

values-zh-rCN/strings.xml

add translation for zh_CN

---

values-ar/strings.xml

Im finesh Arabic translation>.

Add Arabic Translation

---

values-tr/strings.xml

Turkish Translation for OpenGApps Official App(%80 completed.)

Completed %80 of Turkish Translation

---

values-sk/strings.xml

Update strings.xml SK

---

values-ko/strings.xml

Korean Translation

---

values-da/strings.xml

Add support for Danish (Denmark)

Danish tranlation file: values-da/strings.xml

---

values-it/strings.xml

This is my proposal for Italian language update
Take care that for strings.xml is you use"'" as character you should add "\". Ex.  l'\app....
Thanks.

Update Italian language

---

values-cs/strings.xml

First version of my Czech translation

Added Czech translation

---

values-pt-rBR/strings.xml

Updated my own author username, it was incorrect.

Updated author username.

---

values-zh-rTW/strings.xml

from zh-rCN translation, converted by OpenCC (https://github.com/BYVoid/OpenCC)
It's better than nothing, anyway.

add zh-rTW translation

---

values-de/strings.xml

In addition to my changes I would suggest to harmonize the mixture of informal ("Du") and formal ("Sie") speech into one form. I would prefer the formal speech. What do others think?

Corrections and translations of new texts (German)

---

values-ru/strings.xml

Update russian strings for 1.1

---

values-in/strings.xml

fix disconcerting word for "pre"

fix disconcerting word

---

values-pt-rBR/strings.xml

Translated file from scratch, and with that, comes the translation of the new strings for the new version of the app.

Brazilian portuguese - strings.xml translated from scratch

---

values-pt-rBR/strings.xml

Correcting wrong translation by context.

---

values-es/strings.xml

A few of the strings were yet to be translated, now everything is in
place.

Finished spanish translation

---

values-es/strings.xml

Fixed typos and changed some text for better understanding.

Finished spanish translation.

---

values-it/strings.xml

I've fixed some little problems and improved some translations.
Still debating if it is necessary to go full kung-fu on the text since there are some inconsitencies like the mixed use of 'Download' and 'Scarica'. Not really a problem, but I don't like it :)

Italian translation fixes and improvements

---

values-fr/strings.xml

The french word for package is paquet.

Translate "package" in french translation
